name: Build and Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: All things angular Build and Deploy
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1 ## replace by latest version without it you will see Expected format {org}/{repo}[/path]@ref. Actual 'AhsanAyaz/angular-deploy-gh-pages-actions',Input string was not in a correct format.
      with:
        build_configuration: production # The build environment for the app. please look configurations in your angular.json
        base_href: https://agroinnovative.github.io/agro-innovative/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: gh-pages # The branch the action should deploy to.
        angular_dist_build_folder: dist/website # The folder where your project is supposed to be after running ng build by the action.
